# SPDX-FileCopyrightText: 2021 The thiol developers
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
    "thiol-ast-lowering",
    "thiol-hir",
    "thiol-syntax",
    "thiol-typeck",
    "thiolc"
]